# Generated by Django 3.2.9 on 2022-02-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
