# Generated by Django 3.2.9 on 2022-03-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular_list',
            field=models.IntegerField(default=0, verbose_name='popular_list'),
        ),
    ]
