# Generated by Django 3.2.9 on 2022-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaster', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
