# Generated by Django 3.2.9 on 2022-03-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaster', '0004_auto_20220303_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aothor',
            new_name='author',
        ),
    ]
