# Generated by Django 3.2.9 on 2022-03-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaster', '0007_auto_20220310_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
