# Generated by Django 3.2.9 on 2022-03-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaster', '0008_product_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(blank=True),
        ),
    ]
