# Generated by Django 3.2.9 on 2022-03-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaster', '0009_alter_product_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_date',
        ),
    ]
